
apiVersion: v1
kind: Service
metadata:
  name: timer-svc
  namespace: countdown
spec:
  selector:
    app: timer-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
