
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timer-ing
  namespace: countdown
spec:
  rules:
    - host: timer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: timer-svc
                port:
                  number: 80
